### ISSUE TITLE
Start Rhasspy on Boot

### ISSUE THREAD

**Issue by TADWA-Dyl** [rhasspy/rhasspy#240]
Hi Rhasspy team,

I have installed the Rhasspy 2.5.10 armhf build available as per the [documentation](https://rhasspy.readthedocs.io/en/latest/installation/#debian).

When I run `rhasspy --profile en` Rhasspy works as expected.

I have seen in a previous issue that it is possible to create a systemd [unit file](https://github.com/synesthesiam/rhasspy/issues/86#issuecomment-568601810) to start Rhasspy at boot.

My current issue is that I experience errors when attempting to use this configuration.

It seems that there was previously a [section in the documentation](https://rhasspy.readthedocs.io/en/latest/installation/#running-as-a-service) as referenced by this [response](https://github.com/synesthesiam/rhasspy/issues/86#issuecomment-568607499).

Is there a way to start Rhasspy on boot, and if so, would it be possible for this to be updated in the documentation?

Many thanks,

Dyl

**Comment by poupiote** [comment]
Hi,
You will find tle procedure in french on this link:
https://www.coxprod.org/domotique/lancer-rhasspy-au-demarrage-du-raspberry/3/
Good luck.

**Comment by donburch888** [comment]
I have just been through this, since I don't want to add Docker to a low-speed RasPi Zero which is dedicated to being a Rhasspy satellite. 

My solution is [here](https://community.rhasspy.org/t/rhasspy-as-a-service-without-docker/3174) in English.  Almost identical to the french link poupiote provided, except that I also addressed Reboot/Shutdown which were requiring a sudo password on the nonexistant terminal.
