### ISSUE TITLE
Slots creation

### ISSUE THREAD

**Issue by zikmu76** [rhasspy/rhasspy#34]
Hello,
I have a problem creating slots.
I installed the docker version 2.5.0-pre. everything works normally. Profil : fr
When I want to create a slot nothing happens when I save. when I come back to the slots page it's empty. nothing is saved
Thanks for your help.
Have a good day
Best regards

**Comment by synesthesiam** [comment]
Did you create a new slot first?

**Comment by keith721** [comment]
Just noticed this same behavior.  I'll try creating a single new slot first, then reloading all my previously existing 2.4.x slots.

Nope, didn't change the results.  The slots file in my profile directory DOES contain all the slots I copied in, though.  So that's good.

**Comment by parasaurolophus** [comment]
Not exactly the same issue, but FWIW in a fresh install of the 2.5.0 docker based version with no pre-existing profile, I had to manually create the $HOME/.config/rhasspy/profile/en/slots directory in order for "New Slot" to work. Once I did so, I was able to use the web UI to create and edit slots files.

Is it possible that there is some strangeness with file ownership / permissions that could affect users with pre-existing profile files? The whole directory tree under $HOME/.config/rhasspy ended up owned by root even though I launched the docker container without sudo after adding myself to the docker group -- i.e. "docker run..." rather than "sudo docker run..." -- even though that is very bad practice. I'm going to experiment with starting over and passing the user and group pids for myself into the "docker run..." command to see if that changes things.

**Comment by keith721** [comment]
@parasaurolophus nailed it, on the head.  
Without the slots sub-directory being present in the profile directory, the service could not properly create and save new slot files.

**Comment by synesthesiam** [comment]
> The whole directory tree under $HOME/.config/rhasspy ended up owned by root even though I launched the docker container without sudo after adding myself to the docker group

This happens because the user *inside* the Docker container is `root` by default. You need to add this to your `docker run` command:

```sh
$ docker run ... --user "$(id -u):$(id -g)" ...
```

Beware that this can sometimes fail to access the microphone directly, which is why I don't do it by default in the documentation.

Rhasspy always tries to create the slot sub-directories before writing the slot, so this must be a permissions issue. After switching between Docker and a venv install, I often have to do:

```sh
$ sudo chown -R $USER:$USER ~/.config/rhasspy
```
