### ISSUE TITLE
WISH: handle volume

### ISSUE THREAD

**Issue by KiboOst** [rhasspy/rhasspy#37]
Here some explanation : https://community.rhasspy.org/t/change-raspberry-volume/791

Setting volume seems something really important for vocal assistant. 

Actually we have to ssh on the Pi and send command.

Could Rhasspy handle such volume command ?
Why not having a command access to send other such commands like we do over ssh ?

**Comment by koenvervloesem** [comment]
An MQTT topic to set the volume for a specific site ID would be useful indeed.

**Comment by KiboOst** [comment]
Any idea about having this ?

**Comment by DeadEnded** [comment]
I will add myself to this request.
Currently I have a cron job that turns volume up/down and certain times of the day from the host - but was hoping to automate it through Node-Red/HA.  Example, when baby's door is shut, turn down the volume.

I have tried to do this through a slot program, but it was explained to me these run during training, not execution - so that didn't work.  I also tried from Node-Red but that requires you to install packages, and change permissions/groups... and doing that on every container update is tedious.  I know it would work because I can adjust from within the Rhasspy container - its just not exposed to be executed from outside.

Exposing the volume through API and MQTT would be fantastic.  I am not certain how difficult this would be (need to use the audio play device specified in the command, but I expect the amazing people working on this already know way more than I do on how to do it).

Because I would love to help, I'm going to start looking at this to see if I can figure out even a first step (I imagine looking at how the other API's work would be a start).  But I highly doubt I'll get past the first step!

Thanks!
DeadEnd

**Comment by koenvervloesem** [comment]
For reference: [discussion about this on the forum](https://community.rhasspy.org/t/create-volume-control-endpoints/1373).

**Comment by synesthesiam** [comment]
Another idea here: https://github.com/rhasspy/rhasspy/issues/112

I can modify [rhasspy-speakers-cli-hermes](https://github.com/rhasspy/rhasspy-speakers-cli-hermes/) to look for WAVE metadata with a requested volume change, run the WAV data through sox, and play the post-processed audio.

To make this work, we'd need to modify anything that puts out a `playBytes` message to optionally include a volume setting. The nice thing is you could have different volumes for different services.

**Comment by synesthesiam** [comment]
Got a start on the WAV metadata manipulation: https://github.com/synesthesiam/wav-chunk

**Comment by synesthesiam** [comment]
This will be part of 2.5.8

**Comment by synesthesiam** [comment]
Present now in 2.5.8 :)
