### ISSUE TITLE
English STT with kaldi is sexist

### ISSUE THREAD

**Issue by Mic92** [rhasspy/rhasspy#64]
While it understands me (non-native speaker, male) well it struggles to understand my girlfriend (native speaker, female). It works better when she tries to speak with a deeper voice also her natural voice is not that high. I will follow up with audio samples soon. The question is what data was the model trained on? Was it only contained male voices?
Has anyone made similar experience? My current sample set is quite small. I try to increase it.

**Comment by Mic92** [comment]
I don't remember this behavior with pocketsphinx. I will test soonish.

**Comment by synesthesiam** [comment]
The Kaldi English model comes from [Zamia Speech](https://github.com/gooofy/zamia-speech), and was trained on [these open datasets](https://github.com/gooofy/zamia-speech/#speech-corpora). For English, this seems to include [LibreSpeech](http://www.openslr.org/12/), [LJSpeech](https://keithito.com/LJ-Speech-Dataset/), [Mozilla Common Voice](https://voice.mozilla.org/en/data), [TED-LIUM](https://www.openslr.org/51/), [VoxForge](http://www.repository.voxforge1.org/downloads/SpeechCorpus/Trunk/Audio/Main/16kHz_16bit/), and [Zamia](http://goofy.zamia.org/zamia-speech/corpora/zamia_en/).

The majority of the dataset comes from LibreSpeech, with TED-LIUM and Common Voice being the next two largest ones. LibreSpeech appears to be quite well balanced (1201 female, 1283 male). TED-LIUM seems to have about 2x males/females (based on [the paper](http://www.lrec-conf.org/proceedings/lrec2012/pdf/698_Paper.pdf)), and Common Voice lists itself as 46% male/13% female (rest unreported?).

So it would seem yes, there is definitely a bias towards male speakers in the datasets. I'd hesitate to call it "sexist", however, since (to my knowledge) Kaldi itself does not have any mathematical notion of sex in the nnet3 recipes (used to train this model).

If she's willing, I would encourage your girlfriend to donate to [Mozilla Common Voice](https://voice.mozilla.org/en). I keep an eye on that dataset and [this excellent corpora listing](https://github.com/JRMeyer/open-speech-corpora). I hope to start training my own Kaldi models soon, and a greater diversity in the dataset would be most welcome.

**Comment by Mic92** [comment]
Thanks for the explanation. I will also checkout some other models for example wav2letter: https://talonvoice.com/research/
