### ISSUE TITLE
No matching distribution found for rhasspy-server-hermes~=2.5.1 (from rhasspy==2.5.0)

### ISSUE THREAD

**Issue by arpagor62970** [rhasspy/rhasspy#84]
make install ->
ERROR: Could not find a version that satisfies the requirement rhasspy-server-hermes~=2.5.1 (from rhasspy==2.5.0) (from versions: 2.5.0)
ERROR: No matching distribution found for rhasspy-server-hermes~=2.5.1 (from rhasspy==2.5.0)
make: *** [Makefile:146: install-rhasspy] Error 1

**Comment by lricher1** [comment]
Hi 
have you find a solution at this problem ?
thanks

**Comment by arpagor62970** [comment]
No solution now

**Comment by synesthesiam** [comment]
Version 2.5.2 is up: https://pypi.org/project/rhasspy-server-hermes/

**Comment by arpagor62970** [comment]
Same problem with New version

Le lun. 20 juil. 2020 à 15:52, Michael Hansen <notifications@github.com> a
écrit :

**Comment by lricher1** [comment]
+1

**Comment by synesthesiam** [comment]
Are you doing `./configure --enable-in-place`? That should make use of the source code directly instead of trying to pull down packages from PyPI.

EDIT: I just noticed that readthedocs hadn't re-built in a month, so the documentation has been out of date this whole time regarding the venv installation!
