### ISSUE TITLE
[Question] STT - TTS to invoke a script integration

### ISSUE THREAD

**Issue by himuura** [rhasspy/rhasspy#97]
Congrats for the work mate! I''ve been a "follower" of JASPER a.k.a JARVIS for a couple of years now and i'm kind of curious about one thing on Rhasspy...Imagine that i have a script (.sh) that returns a value. How can i integrate that so if i say "Hey BANANA" (beep sound) "Tell me the temperature of my raspberry" and it would swiftly say "Your raspberry is XX degrees" assuming the script executes a vcgencmd measure_temp for instance. How easy is it to integrate? Again, congrats for the project, great work indeed!

**Comment by synesthesiam** [comment]
Thanks! One easy way might to use the [Command Intent Handler](https://rhasspy.readthedocs.io/en/latest/intent-recognition/#command), which just calls a script every time a voice command is recognized.

That can be tricky to get right if you're using Docker though, since the script is run inside the container. In that case, I usually recommend people just expose port 12183 on their container and connect an MQTT client to it (like `mosquitto_sub`) to listen for `hermes/intent/<INTENT_NAME>` messages. Websockets are also available for something like [Node-RED](https://rhasspy.readthedocs.io/en/latest/usage/#node-red).

For "Hey BANANA", you can use the [Raven wake word system](https://rhasspy.readthedocs.io/en/latest/wake-word/#raven) to train your own wake word with 3 samples. Then, your [voice command template](https://rhasspy.readthedocs.io/en/latest/training/#sentencesini) might be something like:

```
[RPiTemperature]
tell me the temperature of my raspberry
```

When recognized, this will deliver a JSON message on MQTT topic `hermes/intent/RPiTemperature`

**Comment by himuura** [comment]
Hi! Took me a lot to get back to you! I'm kind of confused with the documentation...So, i'm not using docker, it's local install.
The .sh just has the command "vcgencmd measure_temp arm". Can you set me up with this example so i can understand the logic behind?
Do i just need to add to the profile:
"intent": {
  "system": "command",
  "command": {
    "program": "/root/scripts/pitemp.sh",
    "arguments": []
  }
}
And it will work and tell the temperature out of the box or do i also need:
{
  "intent": {
    "name": "PiTemp",
    "confidence": 1.0
  },
  "entities": [
    { "entity": "name",
      "value": "pi 3 B temperature" }
               ],
  "text": "what is the temperature of 3 B"
}

Can you please shed some light? Thanks in advance @synesthesiam

**Comment by himuura** [comment]
Well, i got my intent recognized but i cannot seem to link it to the script that i want to execute. I dont actually know where to specify that when the intent X is recognized, script Y must be executed. Can anyone help a brother out?

**Comment by synesthesiam** [comment]
Should be something like this in your profile:

```json
"handle": {
  "system": "command",
  "command": {
      "program": "/path/to/program",
      "arguments": []
  }
}
```

Your command will receive the JSON intent on standard in. You can do whatever in the script, and then you should repeat the JSON back on standard out.

You can add extra fields to the JSON going out to get Rhasspy to speak. See [this example script](https://github.com/synesthesiam/rhasspy/blob/master/bin/mock-commands/handle.py).
